name: Lint

on:
  - push
  - pull_request

jobs:
  reviewdog:
    strategy:
      matrix:
        ruby: [2.6]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1.40.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.ruby }}-
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin 
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin v$REVIEWDOG_VERSION
          echo ::add-path::$HOME/bin
        env:
          REVIEWDOG_VERSION: "0.10.1"
      - name: bundle install
        run: |
          bundle config deployment true
          bundle config path vendor/bundle
          bundle install --jobs 4
      - name: Run reviewdog
        run: reviewdog -fail-on-error -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
